window.CPR_FLASHCARDS = [
  { id: "n01", deck: "numbers", topic: "Frecuencia", front: "¿Frecuencia de compresiones en adulto/niño/lactante?", back: "100–120 por minuto para todas las edades en BLS." },
  { id: "n02", deck: "numbers", topic: "Profundidad en adulto", front: "¿Profundidad de las compresiones en el adulto?", back: "Al menos 2 inches (5 cm), no más de 2.4 inches (6 cm)." },
  { id: "n03", deck: "numbers", topic: "Profundidad en niño", front: "¿Profundidad de las compresiones en el niño?", back: "Cerca de 2 inches, o un tercio del pecho de adelante hacia atrás." },
  { id: "n04", deck: "numbers", topic: "Profundidad en lactante", front: "¿Profundidad de las compresiones en el lactante?", back: "Cerca de 1½ inches (4 cm), o un tercio del diámetro AP." },
  { id: "n05", deck: "numbers", topic: "Relación en adulto", front: "¿Relación de RCP en adulto (sin vía aérea avanzada)?", back: "30:2 con uno o dos rescatistas." },
  { id: "n06", deck: "numbers", topic: "Peds un rescatista", front: "¿Niño o lactante, un rescatista, relación?", back: "30:2." },
  { id: "n07", deck: "numbers", topic: "Peds dos rescatistas", front: "¿Niño o lactante, dos rescatistas, sin vía aérea avanzada?", back: "15:2." },
  { id: "n08", deck: "numbers", topic: "Verificación del pulso", front: "¿Tiempo máximo de verificación del pulso?", back: "10 segundos. Si duda, inicie RCP." },
  { id: "n09", deck: "numbers", topic: "Cambio", front: "¿Cambiar a quien comprime cada?", back: "Unos 2 minutos (o 5 ciclos de 30:2)." },
  { id: "n10", deck: "numbers", topic: "Pausa", front: "¿Mantener las interrupciones por debajo de?", back: "10 segundos cuando pueda." },
  { id: "n11", deck: "numbers", topic: "CCF", front: "¿Meta de la fracción de compresiones torácicas?", back: "Al menos 60%; los equipos de alto rendimiento apuntan a ~80%+." },
  { id: "n12", deck: "numbers", topic: "Duración de la ventilación", front: "¿Cada ventilación de rescate dura?", back: "Cerca de 1 segundo, solo lo suficiente para elevación visible del tórax." },
  { id: "n13", deck: "numbers", topic: "Ventilación de rescate en adulto", front: "¿Adulto con pulso, sin respiración: frecuencia?", back: "1 ventilación cada 6 segundos (~10/min). Vuelva a comprobar el pulso ~ cada 2 minutos." },
  { id: "n14", deck: "numbers", topic: "Ventilación de rescate peds", front: "¿Lactante/niño con pulso, respiración inadecuada?", back: "1 ventilación cada 2–3 segundos (20–30/min)." },
  { id: "n15", deck: "numbers", topic: "Vía aérea avanzada en adulto", front: "¿RCP en adulto con vía ET/supraglótica?", back: "Compresiones continuas. 1 ventilación cada 6 segundos." },
  { id: "n16", deck: "numbers", topic: "Vía aérea avanzada peds", front: "¿Niño/lactante con vía aérea avanzada?", back: "Compresiones continuas. 1 ventilación cada 2–3 segundos (20–30/min)." },
  { id: "n17", deck: "numbers", topic: "FC 60", front: "¿Inicie RCP en un niño/lactante si la FC es?", back: "Menos de 60/min con signos de mala perfusión (a pesar de oxigenación/ventilación)." },
  { id: "n18", deck: "numbers", topic: "Ciclos", front: "¿Cinco ciclos de 30:2 ≈ ?", back: "Unos 2 minutos." },
  { id: "n19", deck: "numbers", topic: "Cerebro", front: "¿El daño cerebral puede comenzar después de unos?", back: "4–6 minutos sin flujo sanguíneo." },
  { id: "n20", deck: "numbers", topic: "Aprobado escrito", front: "¿Puntaje típico de aprobado escrito de AHA?", back: "84% (21/25 en un examen de 25 preguntas)." },
  { id: "n21", deck: "numbers", topic: "OVACE en lactante", front: "¿Ciclo de atragantamiento grave en lactante consciente?", back: "5 palmadas en la espalda, 5 empujes torácicos, repetir." },
  { id: "n22", deck: "numbers", topic: "Edad del niño", front: "¿Rango de edad de “niño” en BLS?", back: "Desde aproximadamente 1 año hasta la pubertad." },
  { id: "n23", deck: "numbers", topic: "Edad del lactante", front: "¿Edad de “lactante” en BLS?", back: "Menor de 1 año (no recién nacido de sala de partos/NRP)." },
  { id: "n24", deck: "numbers", topic: "DEA peds", front: "¿Parches/llave pediátricos del DEA se usan por lo general por debajo de?", back: "Unos 8 años o 25 kg (55 lb): siga la etiqueta del dispositivo." },
  { id: "n25", deck: "numbers", topic: "Aspirina", front: "¿Dosis de aspirina Heartsaver que a menudo se enseña para infarto?", back: "Mastique 162–325 mg si no es alérgico y el protocolo lo permite, después de llamar al 911." },
  { id: "n26", deck: "numbers", topic: "Azúcar", front: "¿Glucosa oral para un diabético bajo que responde?", back: "Unos 15–20 gramos de carbohidrato rápido si pueden tragar." },
  { id: "n27", deck: "numbers", topic: "911 por convulsión", front: "¿Llame al 911 por una convulsión si dura?", back: "Más de 5 minutos, o primera convulsión, lesión, embarazo, o no despiertan." },
  { id: "n28", deck: "numbers", topic: "Hemorragia nasal", front: "¿Pellizque una hemorragia nasal unos?", back: "10 minutos en la parte blanda de la nariz, inclinarse hacia adelante." },
  { id: "n29", deck: "numbers", topic: "Torniquete", front: "¿Colocación del torniquete?", back: "2–3 inches por encima de la herida, no sobre una articulación, lo bastante apretado para detener la hemorragia. Escriba la hora." },
  { id: "n30", deck: "numbers", topic: "Sostener epi", front: "¿Cuánto tiempo sostener un EpiPen típico en el muslo?", back: "Siga el dispositivo (a menudo unos 3 segundos). Anote la hora. Llame al 911." },
  { id: "n31", deck: "numbers", topic: "Relación NRP", front: "¿Relación de recién nacido en sala de partos (NRP, no BLS)?", back: "3:1 compresiones a ventilaciones. No use esto en un lactante de 6 meses en público." },
  { id: "n32", deck: "numbers", topic: "Peds no presenciado", front: "¿Solo, sin teléfono, paro de niño/lactante no presenciado: RCP primero durante?", back: "Unos 2 minutos, luego vaya a activar el SEM / conseguir DEA (puede llevar a un lactante pequeño)." },
  { id: "n33", deck: "numbers", topic: "Ciclo de trabajo", front: "¿Ciclo de trabajo de la compresión?", back: "Cerca de 50% abajo / 50% recoilo." },
  { id: "n34", deck: "numbers", topic: "Veneno", front: "¿Número de Control de Envenenamientos de EE. UU.?", back: "1-800-222-1222." },
  { id: "n35", deck: "numbers", topic: "Inclinación en embarazo", front: "¿Si no puede desplazar el útero, inclinación a la izquierda de unos?", back: "Unos 15–30 grados, permitiendo aún las compresiones. Se prefiere el desplazamiento manual a la izquierda si tiene manos." },

  { id: "s01", deck: "sequence", topic: "BLS en adulto", front: "¿Secuencia de un rescatista en adulto después de la seguridad de la escena?", back: "Toque/grite → llame al 911 y DEA → compruebe respiración/pulso ≤10 s → 30 compresiones → 2 ventilaciones → repita. DEA en cuanto llegue." },
  { id: "s02", deck: "sequence", topic: "CAB", front: "¿Qué significa C-A-B?", back: "Compresiones, vía Aérea, ventilación (Breathing). (Ahogamiento: las ventilaciones son especialmente urgentes.)" },
  { id: "s03", deck: "sequence", topic: "Pasos del DEA", front: "¿Pasos del DEA en orden?", back: "Encienda → descubra el pecho → parches (siga las imágenes) → apártese para analizar → desfibrile si se aconseja (apártese) → RCP de inmediato. Deje los parches puestos." },
  { id: "s04", deck: "sequence", topic: "Después de la descarga", front: "¿Qué hace justo después de una descarga?", back: "Reanude las compresiones de inmediato. No compruebe un pulso primero." },
  { id: "s05", deck: "sequence", topic: "Sin descarga", front: "¿El DEA dice que no se aconseja descarga?", back: "RCP de inmediato hasta que vuelva a analizar o la persona se recupere." },
  { id: "s06", deck: "sequence", topic: "OVACE sin respuesta", front: "El adulto atragantado deja de responder. ¿Siguiente?", back: "Al suelo → RCP → mire en la boca antes de las ventilaciones → quite el objeto solo si lo ve." },
  { id: "s07", deck: "sequence", topic: "Atragantamiento en lactante", front: "¿OVACE grave en lactante consciente?", back: "Boca abajo, cabeza más baja: 5 palmadas en la espalda → boca arriba: 5 empujes torácicos → repita hasta que se despeje o dejen de responder (entonces RCP)." },
  { id: "s08", deck: "sequence", topic: "Inclinación de la cabeza", front: "¿Cómo abre una vía aérea típica de adulto?", back: "Inclinación de la cabeza / elevación del mentón. Tracción mandibular si sospecha lesión de columna cervical; incline de todos modos si no puede ventilar." },
  { id: "s09", deck: "sequence", topic: "Sitios del pulso", front: "¿Sitios de verificación del pulso: adulto, niño, lactante?", back: "Adulto: carótida. Niño: carótida o femoral. Lactante: braquial (femoral está bien)." },
  { id: "s10", deck: "sequence", topic: "Posición de las manos en adulto", front: "¿Posición de las manos en el adulto?", back: "Talón de la mano en la mitad inferior del esternón, la otra mano encima. No el xifoides." },
  { id: "s11", deck: "sequence", topic: "Manos en lactante", front: "¿Técnicas de compresión en el lactante?", back: "Rescatista solo: 2 dedos debajo de la línea de los pezones. Dos rescatistas: 2 pulgares envolventes (preferido)." },
  { id: "s12", deck: "sequence", topic: "Cuándo detenerse", front: "¿Cuándo puede detener la RCP?", back: "Signos de vida / RCE, el SEM asume, escena insegura, no puede continuar físicamente, o un DNR válido que aplique." },
  { id: "s13", deck: "sequence", topic: "Recuperación", front: "¿Cuándo está bien la posición de recuperación?", back: "Sin respuesta pero respirando con normalidad, sin trauma que prohíba voltear. Nunca en lugar de la RCP." },
  { id: "s14", deck: "sequence", topic: "Agónico", front: "¿Los jadeos agónicos significan?", back: "No es respiración normal. Inicie RCP." },
  { id: "s15", deck: "sequence", topic: "Cambio de equipo", front: "¿Mejor momento para cambiar a quien comprime?", back: "Durante el análisis del DEA o cada 2 minutos, con las manos listas para reiniciar al instante." },
  { id: "s16", deck: "sequence", topic: "Circuito cerrado", front: "¿Comunicación de circuito cerrado?", back: "Asigne por nombre → ellos repiten la tarea → confirman cuando está hecha." },
  { id: "s17", deck: "sequence", topic: "BVM de dos personas", front: "¿Mejor método de bolsa-máscara?", back: "Una persona sello E-C a dos manos, la otra aprieta. Observe la elevación del tórax." },
  { id: "s18", deck: "sequence", topic: "Presenciado vs no en niño", front: "¿Solo: colapso presenciado de un niño vs encontrado caído, sin teléfono?", back: "Súbito presenciado: llame/DEA primero. Encontrado caído: ~2 min de RCP, luego vaya por ayuda." },
  { id: "s19", deck: "sequence", topic: "Paro por opioides", front: "¿Sospecha de opioides, sin pulso?", back: "RCP primero. Naloxona en cuanto esté disponible. DEA. No espere la naloxona para iniciar las compresiones." },
  { id: "s20", deck: "sequence", topic: "Pulso con opioides", front: "¿Opioides, pulso presente, no respira?", back: "Vía aérea, ventilaciones de rescate, naloxona. No 30:2 a menos que pierdan el pulso / reglas de FC para peds." },
  { id: "s21", deck: "sequence", topic: "Ahogamiento", front: "¿Prioridad BLS en ahogamiento después de que usted está seguro?", back: "Llévelos a una superficie firme. RCP con ventilaciones (hipoxia). DEA cuando esté lo bastante seco. No Heimlich de rutina." },
  { id: "s22", deck: "sequence", topic: "RCP en embarazo", front: "¿Extras del paro visiblemente embarazado?", back: "RCP estándar + DEA. Desplazamiento uterino manual a la izquierda. Dígale al SEM dos pacientes." },
  { id: "s23", deck: "sequence", topic: "Ventilación fallida", front: "¿El pecho no se eleva?", back: "Reabra la vía aérea, selle de nuevo, reintente. Si sigue fallando → piense en OVACE, compresiones, mire en la boca." },
  { id: "s24", deck: "sequence", topic: "Solo con las manos", front: "¿Cuándo está bien la RCP solo con las manos?", back: "No capacitado, no dispuesto o no capaz de dar ventilaciones en un colapso súbito de adulto. No es lo ideal para lactantes/niños/ahogamiento." },
  { id: "s25", deck: "sequence", topic: "Pinza E-C", front: "¿Qué es la pinza E-C?", back: "El pulgar y el índice hacen una C sobre la máscara; los demás dedos una E sobre el hueso de la mandíbula." },

  { id: "a01", deck: "aed", topic: "Encendido", front: "¿Primera acción del DEA?", back: "Enciéndalo (abrir algunas tapas lo hace) y siga las indicaciones." },
  { id: "a02", deck: "aed", topic: "Parches de adulto", front: "¿Colocación estándar de parches en el adulto?", back: "Parte superior derecha del pecho y lado izquierdo debajo de la axila — o como muestren las imágenes. AP si hace falta." },
  { id: "a03", deck: "aed", topic: "Apartarse", front: "¿Por qué gritar “apartarse”?", back: "Una descarga puede pasar a cualquiera que toque a la persona o un camino conductor. Mire, luego desfibrile." },
  { id: "a04", deck: "aed", topic: "Mojado", front: "¿Pecho mojado?", back: "Seque los sitios de los parches. Aléjela del agua estancada. No necesita el cuerpo entero seco como un hueso." },
  { id: "a05", deck: "aed", topic: "Vello", front: "¿Pecho velloso, los parches no se pegan?", back: "Afeite/recorte con rapidez, o use un juego de parches de reserva para arrancar el vello, luego parches nuevos." },
  { id: "a06", deck: "aed", topic: "Parche", front: "¿Parche de medicamento bajo un parche del DEA?", back: "Quítelo, seque el pecho, luego aplique el parche. Guantes si puede." },
  { id: "a07", deck: "aed", topic: "Marcapasos", front: "¿Bulto de marcapasos/DAI?", back: "Parche al menos a una pulgada del dispositivo, no encima." },
  { id: "a08", deck: "aed", topic: "Faltan parches peds", front: "¿Niño, solo parches de adulto?", back: "Úselos. No deje que los parches se toquen. Frente y espalda si hace falta. Una descarga supera a ninguna descarga." },
  { id: "a09", deck: "aed", topic: "Parches peds en adulto", front: "¿Parches pediátricos en un adulto grande?", back: "Demasiada poca energía. Use parches de adulto en adultos." },
  { id: "a10", deck: "aed", topic: "Analizar", front: "¿Durante “analizando”?", back: "No toque. Manos listas, preparado para comprimir." },
  { id: "a11", deck: "aed", topic: "Dejar los parches", front: "¿Después de la primera descarga, los parches?", back: "Se quedan para más análisis/descargas hasta que se transfiere el cuidado." },
  { id: "a12", deck: "aed", topic: "Despierto", front: "¿Puede usar el DEA en una persona que habla?", back: "No. Los DEA son para paro cardíaco, no para dolor de pecho en un paciente consciente." },
  { id: "a13", deck: "aed", topic: "Incendio por oxígeno", front: "¿Oxígeno durante la descarga?", back: "Apartar el oxígeno que fluye del pecho; riesgo de chispa/incendio." },
  { id: "a14", deck: "aed", topic: "DEA en embarazada", front: "¿DEA en una mujer embarazada?", back: "Sí: la misma idea. La supervivencia de la madre es la supervivencia del bebé." },
  { id: "a15", deck: "aed", topic: "Mantenimiento", front: "¿Comprobaciones del DEA en el lugar de trabajo?", back: "Luz de estado, parches vigentes, batería, gabinete despejado, el personal capacitado sabe la ubicación." },
  { id: "a16", deck: "aed", topic: "Compruebe los parches", front: "¿El DEA dice compruebe los parches?", back: "Presione con firmeza, seque, afeite, reemplace los parches. Necesita un circuito." },
  { id: "a17", deck: "aed", topic: "Símbolo público", front: "¿Corazón con un rayo?", back: "Ubicación del DEA." },
  { id: "a18", deck: "aed", topic: "Hormigueo del DAI", front: "¿Siente la descarga del DAI?", back: "Suéltese durante ese pulso si lo nota, luego reanude la RCP. Igual use el DEA en el paro." },
  { id: "a19", deck: "aed", topic: "Minimizar la pausa", front: "¿Cómo acortar la pausa de la descarga?", back: "Comprima hasta que diga apartarse; desfibrile; manos de vuelta al pecho de inmediato." },
  { id: "a20", deck: "aed", topic: "Sin llave pediátrica", front: "El DEA no tiene llave de niño. ¿Lactante en FV?", back: "Use parches de adulto, AP si se superpondrían. Siga las indicaciones." },

  { id: "p01", deck: "peds", topic: "Por qué ventilaciones", front: "¿Por qué los niños necesitan ventilaciones más a menudo que el colapso súbito típico del adulto?", back: "El paro pediátrico suele ser respiratorio (hipoxia) primero, no FV primaria de una coronaria." },
  { id: "p02", deck: "peds", topic: "Pubertad", front: "¿Si no puede distinguir niño vs adulto?", back: "Use métodos de RCP de adulto." },
  { id: "p03", deck: "peds", topic: "Vía aérea del lactante", front: "¿Posición de la cabeza del lactante?", back: "Neutra o ligero olfateo. Una almohadilla bajo los hombros puede ayudar. No hiperextienda." },
  { id: "p04", deck: "peds", topic: "Boca-nariz", front: "¿Boca a boca en el lactante?", back: "Cubra boca y nariz juntas. Ventilación suave de 1 segundo, elevación del tórax." },
  { id: "p05", deck: "peds", topic: "Sin abdominales en lactante", front: "¿Por qué no Heimlich en lactantes?", back: "Lesión de hígado y órganos. Use palmadas en la espalda y empujes torácicos si está consciente." },
  { id: "p06", deck: "peds", topic: "Barrido a ciegas", front: "¿Barrido digital a ciegas?", back: "Nunca. Puede alojar el objeto más adentro. Solo barre lo que ve." },
  { id: "p07", deck: "peds", topic: "Dos pulgares", front: "¿Dos pulgares envolventes?", back: "Pulgares en el esternón inferior, los dedos sostienen la espalda. Preferido con dos rescatistas en un lactante." },
  { id: "p08", deck: "peds", topic: "Braquial", front: "¿Dónde está el pulso braquial?", back: "Parte interna del brazo superior, entre bíceps y tríceps." },
  { id: "p09", deck: "peds", topic: "Prevención en la cadena", front: "¿Eslabón extra en la cadena pediátrica?", back: "Prevención (agua, sueño, lesiones) más el reconocimiento habitual, RCP, DEA, ALS, recuperación." },
  { id: "p10", deck: "peds", topic: "Teléfono en la escena", front: "¿Paro de niño no presenciado pero tiene un celular?", back: "911 por altavoz e inicie RCP. No tiene que irse." },
  { id: "p11", deck: "peds", topic: "Cambio de relación", front: "Llega el segundo rescatista para un niño. ¿Relación?", back: "Cambie de 30:2 a 15:2 hasta una vía aérea avanzada." },
  { id: "p12", deck: "peds", topic: "Uva", front: "¿Ejemplos de peligro alimentario en niños pequeños?", back: "Uvas enteras, hot dogs en rodajas de moneda, nueces, caramelos duros, juguetes pequeños. Corte a lo largo; supervise." },
  { id: "p13", deck: "peds", topic: "NRP vs BLS", front: "¿3:1 es para?", back: "Recién nacido en la sala de partos (NRP), no BLS de lactante en el centro comercial." },
  { id: "p14", deck: "peds", topic: "Manos en niño", front: "¿Manos de compresión en el niño?", back: "Una o dos manos en el esternón inferior: lo que alcance un tercio de profundidad." },
  { id: "p15", deck: "peds", topic: "Cianosis", front: "¿Niño azul que no responde y no respira?", back: "RCP / ventilaciones ahora. No espere a que mejore el color primero." },

  { id: "f01", deck: "firstaid", topic: "Consentimiento", front: "¿Consentimiento implícito?", back: "Sin respuesta (o un niño sin padre en una emergencia verdadera) que necesita atención que salva la vida." },
  { id: "f02", deck: "firstaid", topic: "FAST", front: "¿FAST?", back: "Cara, Brazo, Habla, Tiempo de llamar al 911. Anote la última vez que se le vio bien." },
  { id: "f03", deck: "firstaid", topic: "Hemorragia", front: "¿Primer paso para la mayoría de las hemorragias?", back: "Presión directa. Luego empaque / torniquete si amenaza la vida en una extremidad." },
  { id: "f04", deck: "firstaid", topic: "Choque", front: "¿Posición de choque en primeros auxilios?", back: "Acostado, abrigado, controle la hemorragia, NPO si es posible la cirugía, SEM." },
  { id: "f05", deck: "firstaid", topic: "Infarto", front: "¿Pistas de infarto?", back: "Presión en el pecho, falta de aire, sudor, náuseas, dolor en brazo/mandíbula/espalda. Mujeres/personas mayores/diabéticos pueden ser atípicos. 911, no un auto particular si puede evitarlo." },
  { id: "f06", deck: "firstaid", topic: "Anafilaxia", front: "¿Fármaco de primera línea para anafilaxia?", back: "Epinefrina en la parte externa del muslo. Luego 911. El antihistamínico no basta para choque/estridor." },
  { id: "f07", deck: "firstaid", topic: "Convulsión", front: "¿Durante una convulsión?", back: "Proteja la cabeza, despeje el espacio, cronométrala, nada en la boca, no los sujete." },
  { id: "f08", deck: "firstaid", topic: "Diabético bajo", front: "¿Diabético tembloroso, sudoroso, despierto?", back: "Si pueden tragar: 15–20 g de azúcar. Si no responden: no azúcar oral, 911, glucagón si está capacitado." },
  { id: "f09", deck: "firstaid", topic: "Quemadura", front: "¿Enfríe una quemadura térmica con?", back: "Agua fría (no hielo pegado a la piel). Cubierta limpia y seca. 911 para grande/cara/vía aérea/eléctrica/química." },
  { id: "f10", deck: "firstaid", topic: "Columna", front: "¿Cuándo proteger la columna?", back: "Mecanismo significativo (caída, zambullida, choque) más dolor de cuello, entumecimiento o falta de respuesta. Tracción mandibular para la vía aérea." },
  { id: "f11", deck: "firstaid", topic: "Golpe de calor", front: "¿Golpe de calor vs agotamiento?", back: "Golpe: caliente y alterado: enfríe rápido, 911. Agotamiento: aún sensible, reposo/enfríe/líquidos si pueden beber." },
  { id: "f12", deck: "firstaid", topic: "Buen Samaritano", front: "¿Idea del Buen Samaritano?", back: "Ayuda de buena fe dentro de la capacitación, no imprudente, por lo general no remunerada. No cubre el abandono ni desfibrilar a una persona que habla." },
  { id: "f13", deck: "firstaid", topic: "Abandono", front: "¿Abandono?", back: "Usted inicia la atención, aún lo necesitan, se va sin una entrega adecuada y sin una razón de seguridad." },
  { id: "f14", deck: "firstaid", topic: "EPP", front: "¿Precauciones estándar?", back: "Trate toda sangre/fluidos corporales como infecciosos. Guantes, barreras, higiene de las manos, reporte exposiciones." },
  { id: "f15", deck: "firstaid", topic: "Empalado", front: "¿Objeto empalado?", back: "Estabilícelo en su lugar a menos que bloquee la vía aérea. No lo saque en el campo por hábito." },
  { id: "f16", deck: "firstaid", topic: "Diente", front: "¿Diente permanente avulsionado?", back: "Recójalo por la corona, manténgalo húmedo (leche/solución salina), dentista lo antes posible. No restregue la raíz." },
  { id: "f17", deck: "firstaid", topic: "Veneno", front: "¿Veneno ingerido?", back: "Llame a Control de Envenenamientos o al 911. No adivine antídotos ni fuerce el vómito." },
  { id: "f18", deck: "firstaid", topic: "Escena", front: "¿Primera acción de primeros auxilios siempre?", back: "Seguridad de la escena (y su EPP). Luego consentimiento / consentimiento implícito." },
  { id: "f19", deck: "firstaid", topic: "NPO en ACV", front: "¿Por qué nada por boca en un ACV?", back: "Pueden no tragar con seguridad: aspiración." },
  { id: "f20", deck: "firstaid", topic: "Tarjeta", front: "¿Este laboratorio de práctica emite una tarjeta AHA?", back: "No. Solo un instructor autorizado después del curso oficial y la prueba de destrezas puede emitir una tarjeta." }
];
