window.CPR_FLASHCARDS = [
  { id: "n01", deck: "numbers", topic: "Rate", front: "Adult/child/infant compression rate?", back: "100–120 per minute for all ages in BLS." },
  { id: "n02", deck: "numbers", topic: "Adult depth", front: "Adult compression depth?", back: "At least 2 inches (5 cm), not more than 2.4 inches (6 cm)." },
  { id: "n03", deck: "numbers", topic: "Child depth", front: "Child compression depth?", back: "About 2 inches, or one-third the chest front-to-back." },
  { id: "n04", deck: "numbers", topic: "Infant depth", front: "Infant compression depth?", back: "About 1½ inches (4 cm), or one-third AP diameter." },
  { id: "n05", deck: "numbers", topic: "Adult ratio", front: "Adult CPR ratio (no advanced airway)?", back: "30:2 with one or two rescuers." },
  { id: "n06", deck: "numbers", topic: "Peds one rescuer", front: "Child or infant, one rescuer, ratio?", back: "30:2." },
  { id: "n07", deck: "numbers", topic: "Peds two rescuers", front: "Child or infant, two rescuers, no advanced airway?", back: "15:2." },
  { id: "n08", deck: "numbers", topic: "Pulse check", front: "Maximum pulse-check time?", back: "10 seconds. If unsure, start CPR." },
  { id: "n09", deck: "numbers", topic: "Switch", front: "Switch compressors every?", back: "About 2 minutes (or 5 cycles of 30:2)." },
  { id: "n10", deck: "numbers", topic: "Pause", front: "Keep interruptions under?", back: "10 seconds when you can." },
  { id: "n11", deck: "numbers", topic: "CCF", front: "Chest compression fraction goal?", back: "At least 60%; high-performance teams aim ~80%+." },
  { id: "n12", deck: "numbers", topic: "Breath length", front: "Each rescue breath lasts?", back: "About 1 second, just enough for visible chest rise." },
  { id: "n13", deck: "numbers", topic: "Adult rescue breathing", front: "Adult with pulse, no breathing: rate?", back: "1 breath every 6 seconds (~10/min). Recheck pulse ~ every 2 minutes." },
  { id: "n14", deck: "numbers", topic: "Peds rescue breathing", front: "Infant/child with pulse, inadequate breathing?", back: "1 breath every 2–3 seconds (20–30/min)." },
  { id: "n15", deck: "numbers", topic: "Adult advanced airway", front: "Adult CPR with ET/supraglottic airway?", back: "Continuous compressions. 1 breath every 6 seconds." },
  { id: "n16", deck: "numbers", topic: "Peds advanced airway", front: "Child/infant with advanced airway?", back: "Continuous compressions. 1 breath every 2–3 seconds (20–30/min)." },
  { id: "n17", deck: "numbers", topic: "HR 60", front: "Start CPR on a child/infant if HR is?", back: "Less than 60/min with signs of poor perfusion (despite oxygenation/ventilation)." },
  { id: "n18", deck: "numbers", topic: "Cycles", front: "Five cycles of 30:2 ≈ ?", back: "About 2 minutes." },
  { id: "n19", deck: "numbers", topic: "Brain", front: "Brain injury can begin after about?", back: "4–6 minutes without blood flow." },
  { id: "n20", deck: "numbers", topic: "Written pass", front: "Typical AHA written pass score?", back: "84% (21/25 on a 25-question exam)." },
  { id: "n21", deck: "numbers", topic: "Infant FBAO", front: "Conscious infant severe choking cycle?", back: "5 back slaps, 5 chest thrusts, repeat." },
  { id: "n22", deck: "numbers", topic: "Child age", front: "BLS “child” age range?", back: "About 1 year to puberty." },
  { id: "n23", deck: "numbers", topic: "Infant age", front: "BLS “infant” age?", back: "Younger than 1 year (not delivery-room newborn/NRP)." },
  { id: "n24", deck: "numbers", topic: "Peds AED", front: "Pediatric AED pads/key typically used under?", back: "About 8 years or 25 kg (55 lb) — follow the device label." },
  { id: "n25", deck: "numbers", topic: "Aspirin", front: "Heartsaver aspirin dose often taught for heart attack?", back: "Chew 162–325 mg if not allergic and protocol allows, after calling 911." },
  { id: "n26", deck: "numbers", topic: "Sugar", front: "Oral glucose for a responsive low diabetic?", back: "About 15–20 grams of fast carbohydrate if they can swallow." },
  { id: "n27", deck: "numbers", topic: "Seizure 911", front: "Call 911 for a seizure if it lasts?", back: "More than 5 minutes, or first seizure, injury, pregnancy, or they don’t wake." },
  { id: "n28", deck: "numbers", topic: "Nosebleed", front: "Pinch a nosebleed for about?", back: "10 minutes on the soft part of the nose, lean forward." },
  { id: "n29", deck: "numbers", topic: "Tourniquet", front: "Tourniquet placement?", back: "2–3 inches above the wound, not on a joint, tight enough to stop bleeding. Write the time." },
  { id: "n30", deck: "numbers", topic: "Epi hold", front: "How long to hold a typical EpiPen in the thigh?", back: "Follow the device (often about 3 seconds). Note the time. Call 911." },
  { id: "n31", deck: "numbers", topic: "NRP ratio", front: "Delivery-room newborn ratio (NRP, not BLS)?", back: "3:1 compressions to breaths. Do not use this on a 6-month-old in public." },
  { id: "n32", deck: "numbers", topic: "Unwitnessed peds", front: "Alone, no phone, unwitnessed child/infant arrest: CPR first for?", back: "About 2 minutes, then go activate EMS / get AED (you may carry a small infant)." },
  { id: "n33", deck: "numbers", topic: "Duty cycle", front: "Compression duty cycle?", back: "About 50% down / 50% recoil." },
  { id: "n34", deck: "numbers", topic: "Poison", front: "U.S. Poison Control number?", back: "1-800-222-1222." },
  { id: "n35", deck: "numbers", topic: "Tilt pregnancy", front: "If you cannot displace the uterus, left tilt about?", back: "About 15–30 degrees, still allowing compressions. Manual left displacement preferred if you have hands." },

  { id: "s01", deck: "sequence", topic: "Adult BLS", front: "One-rescuer adult sequence after scene safety?", back: "Tap/shout → call 911 & AED → check breathing/pulse ≤10 s → 30 compressions → 2 breaths → repeat. AED as soon as it arrives." },
  { id: "s02", deck: "sequence", topic: "CAB", front: "What does C-A-B stand for?", back: "Compressions, Airway, Breathing. (Drowning: breaths are especially urgent.)" },
  { id: "s03", deck: "sequence", topic: "AED steps", front: "AED steps in order?", back: "Power on → bare chest → pads (follow pictures) → clear for analyze → shock if advised (clear) → CPR at once. Leave pads on." },
  { id: "s04", deck: "sequence", topic: "After shock", front: "What do you do right after a shock?", back: "Resume compressions immediately. Do not check a pulse first." },
  { id: "s05", deck: "sequence", topic: "No shock", front: "AED says no shock advised?", back: "CPR immediately until it reanalyzes or the person recovers." },
  { id: "s06", deck: "sequence", topic: "Unresponsive FBAO", front: "Choking adult becomes unresponsive. Next?", back: "To the ground → CPR → look in the mouth before breaths → remove object only if seen." },
  { id: "s07", deck: "sequence", topic: "Infant choke", front: "Conscious infant severe FBAO?", back: "Face-down, head lower: 5 back slaps → face-up: 5 chest thrusts → repeat until it clears or they go unresponsive (then CPR)." },
  { id: "s08", deck: "sequence", topic: "Head-tilt", front: "How do you open a typical adult airway?", back: "Head-tilt / chin-lift. Jaw-thrust if you suspect c-spine injury; tilt anyway if you cannot ventilate." },
  { id: "s09", deck: "sequence", topic: "Pulse sites", front: "Pulse check sites: adult, child, infant?", back: "Adult: carotid. Child: carotid or femoral. Infant: brachial (femoral OK)." },
  { id: "s10", deck: "sequence", topic: "Hand position adult", front: "Adult hand position?", back: "Heel of the hand on the lower half of the sternum, other hand on top. Not the xiphoid." },
  { id: "s11", deck: "sequence", topic: "Infant hands", front: "Infant compression techniques?", back: "Lone rescuer: 2 fingers below nipple line. Two rescuers: 2-thumb encircling (preferred)." },
  { id: "s12", deck: "sequence", topic: "When to stop", front: "When may you stop CPR?", back: "Signs of life / ROSC, EMS takes over, scene unsafe, you cannot physically continue, or a valid DNR that applies." },
  { id: "s13", deck: "sequence", topic: "Recovery", front: "When is recovery position OK?", back: "Unresponsive but breathing normally, no trauma that forbids turning. Never instead of CPR." },
  { id: "s14", deck: "sequence", topic: "Agonal", front: "Agonal gasps mean?", back: "Not normal breathing. Start CPR." },
  { id: "s15", deck: "sequence", topic: "Team switch", front: "Best moment to switch compressors?", back: "During AED analysis or every 2 minutes, with hands hovering to restart instantly." },
  { id: "s16", deck: "sequence", topic: "Closed-loop", front: "Closed-loop communication?", back: "Assign by name → they repeat the task → they confirm when done." },
  { id: "s17", deck: "sequence", topic: "Two-person BVM", front: "Best bag-mask method?", back: "One person two-hand E-C seal, the other squeezes. Watch chest rise." },
  { id: "s18", deck: "sequence", topic: "Witnessed vs not child", front: "Alone: witnessed child collapse vs found down, no phone?", back: "Witnessed sudden: call/AED first. Found down: ~2 min CPR, then go for help." },
  { id: "s19", deck: "sequence", topic: "Opioid arrest", front: "Suspected opioid, no pulse?", back: "CPR first. Naloxone as soon as available. AED. Do not wait on naloxone to start compressions." },
  { id: "s20", deck: "sequence", topic: "Opioid pulse", front: "Opioid, pulse present, not breathing?", back: "Airway, rescue breaths, naloxone. Not 30:2 unless they lose the pulse / HR rules for peds." },
  { id: "s21", deck: "sequence", topic: "Drowning", front: "Drowning BLS priority after you are safe?", back: "Get them to a firm surface. CPR with breaths (hypoxia). AED when dry enough. No routine Heimlich." },
  { id: "s22", deck: "sequence", topic: "Pregnancy CPR", front: "Visibly pregnant arrest extras?", back: "Standard CPR + AED. Manual left uterine displacement. Tell EMS two patients." },
  { id: "s23", deck: "sequence", topic: "Failed breath", front: "Chest does not rise?", back: "Reopen airway, reseal, retry. Still fail → think FBAO, compressions, look in mouth." },
  { id: "s24", deck: "sequence", topic: "Hands-only", front: "When is hands-only CPR OK?", back: "Untrained, unwilling, or unable to give breaths on an adult sudden collapse. Not the ideal for infants/children/drowning." },
  { id: "s25", deck: "sequence", topic: "EC clamp", front: "What is the E-C clamp?", back: "Thumb and index make a C on the mask; other fingers an E on the jaw bone." },

  { id: "a01", deck: "aed", topic: "Power", front: "First AED action?", back: "Turn it on (opening some lids does this) and follow prompts." },
  { id: "a02", deck: "aed", topic: "Adult pads", front: "Standard adult pad placement?", back: "Upper right chest and left side below the armpit — or as the pictures show. AP if needed." },
  { id: "a03", deck: "aed", topic: "Clear", front: "Why shout “clear”?", back: "A shock can travel into anyone touching the person or conductive path. Look, then shock." },
  { id: "a04", deck: "aed", topic: "Wet", front: "Wet chest?", back: "Wipe pad sites dry. Move out of standing water. You do not need the whole body bone-dry." },
  { id: "a05", deck: "aed", topic: "Hair", front: "Hairy chest, pads won’t stick?", back: "Shave/clip quickly, or use a spare pad set to rip hair, then new pads." },
  { id: "a06", deck: "aed", topic: "Patch", front: "Medicine patch under a pad?", back: "Remove it, wipe the chest, then apply the pad. Gloves if you can." },
  { id: "a07", deck: "aed", topic: "Pacemaker", front: "Pacemaker/ICD lump?", back: "Pad at least an inch off the device, not on top of it." },
  { id: "a08", deck: "aed", topic: "Peds pads missing", front: "Child, only adult pads?", back: "Use them. Do not let pads touch. Front-and-back if needed. A shock beats no shock." },
  { id: "a09", deck: "aed", topic: "Peds pads on adult", front: "Pediatric pads on a large adult?", back: "Too little energy. Use adult pads on adults." },
  { id: "a10", deck: "aed", topic: "Analyze", front: "During “analyzing”?", back: "Do not touch. Hover, ready to compress." },
  { id: "a11", deck: "aed", topic: "Leave pads", front: "After the first shock, pads?", back: "Stay on for more analyses/shocks until care is transferred." },
  { id: "a12", deck: "aed", topic: "Awake", front: "May you AED a talking person?", back: "No. AEDs are for cardiac arrest, not chest pain in a conscious patient." },
  { id: "a13", deck: "aed", topic: "Oxygen fire", front: "Oxygen during shock?", back: "Move flowing oxygen off the chest; spark/fire risk." },
  { id: "a14", deck: "aed", topic: "Pregnant AED", front: "AED on a pregnant woman?", back: "Yes — same idea. Mother’s survival is the baby’s survival." },
  { id: "a15", deck: "aed", topic: "Maintenance", front: "Workplace AED checks?", back: "Status light, in-date pads, battery, unblocked cabinet, trained staff know the location." },
  { id: "a16", deck: "aed", topic: "Check pads", front: "AED says check pads?", back: "Press firmly, dry, shave, replace pads. It needs a circuit." },
  { id: "a17", deck: "aed", topic: "Public symbol", front: "Heart with a lightning bolt?", back: "AED location." },
  { id: "a18", deck: "aed", topic: "ICD tingle", front: "You feel the ICD shock?", back: "Let go during that pulse if you notice it, then resume CPR. Still use the AED in arrest." },
  { id: "a19", deck: "aed", topic: "Minimize pause", front: "How to shorten the shock pause?", back: "Compress until it says clear; shock; hands back on the chest immediately." },
  { id: "a20", deck: "aed", topic: "No pediatric key", front: "AED has no child key. Infant in VF?", back: "Use adult pads, AP if they would overlap. Follow prompts." },

  { id: "p01", deck: "peds", topic: "Why breaths", front: "Why do kids need breaths more often than typical adult sudden collapse?", back: "Pediatric arrest is often respiratory (hypoxia) first, not primary VF from a coronary." },
  { id: "p02", deck: "peds", topic: "Puberty", front: "If you cannot tell child vs adult?", back: "Use adult CPR methods." },
  { id: "p03", deck: "peds", topic: "Infant airway", front: "Infant head position?", back: "Neutral or slight sniffing. A pad under the shoulders may help. Do not overextend." },
  { id: "p04", deck: "peds", topic: "Mouth-nose", front: "Infant mouth-to-mouth?", back: "Cover mouth and nose together. Gentle 1-second breath, chest rise." },
  { id: "p05", deck: "peds", topic: "No abdominal infant", front: "Why no Heimlich on infants?", back: "Liver and organ injury. Use back slaps and chest thrusts if conscious." },
  { id: "p06", deck: "peds", topic: "Blind sweep", front: "Blind finger sweep?", back: "Never. You can lodge the object deeper. Only sweep what you see." },
  { id: "p07", deck: "peds", topic: "Two-thumb", front: "Two-thumb encircling?", back: "Thumbs on lower sternum, fingers support the back. Preferred with two rescuers on an infant." },
  { id: "p08", deck: "peds", topic: "Brachial", front: "Where is the brachial pulse?", back: "Inner upper arm, between biceps and triceps." },
  { id: "p09", deck: "peds", topic: "Chain prevention", front: "Extra link in the pediatric chain?", back: "Prevention (water, sleep, injuries) plus the usual recognition, CPR, AED, ALS, recovery." },
  { id: "p10", deck: "peds", topic: "Phone on scene", front: "Unwitnessed child arrest but you have a cell phone?", back: "Speakerphone 911 and start CPR. You do not have to leave." },
  { id: "p11", deck: "peds", topic: "Ratio change", front: "Second rescuer arrives for a child. Ratio?", back: "Change from 30:2 to 15:2 until an advanced airway." },
  { id: "p12", deck: "peds", topic: "Grape", front: "Toddler food hazard examples?", back: "Whole grapes, hot-dog coins, nuts, hard candy, small toys. Cut lengthwise; supervise." },
  { id: "p13", deck: "peds", topic: "NRP vs BLS", front: "3:1 is for?", back: "Newly born in the delivery room (NRP), not mall/infant BLS." },
  { id: "p14", deck: "peds", topic: "Child hands", front: "Child compression hands?", back: "One or two hands on the lower sternum — whatever reaches one-third depth." },
  { id: "p15", deck: "peds", topic: "Cyanosis", front: "Blue unresponsive child not breathing?", back: "CPR / breaths now. Do not wait for color to improve first." },

  { id: "f01", deck: "firstaid", topic: "Consent", front: "Implied consent?", back: "Unresponsive (or a child with no parent in a true emergency) needing life-saving care." },
  { id: "f02", deck: "firstaid", topic: "FAST", front: "FAST?", back: "Face, Arm, Speech, Time to call 911. Note last known well." },
  { id: "f03", deck: "firstaid", topic: "Bleed", front: "First step for most bleeding?", back: "Direct pressure. Then pack / tourniquet if life-threatening on a limb." },
  { id: "f04", deck: "firstaid", topic: "Shock", front: "First-aid shock position?", back: "Lie down, keep warm, control bleeding, NPO if surgery possible, EMS." },
  { id: "f05", deck: "firstaid", topic: "Heart attack", front: "Heart attack clues?", back: "Chest pressure, SOB, sweat, nausea, pain in arm/jaw/back. Women/elderly/diabetics may be atypical. 911, not a private car if you can help it." },
  { id: "f06", deck: "firstaid", topic: "Anaphylaxis", front: "First-line anaphylaxis drug?", back: "Epinephrine in the outer thigh. Then 911. Antihistamine is not enough for shock/stridor." },
  { id: "f07", deck: "firstaid", topic: "Seizure", front: "During a seizure?", back: "Protect the head, clear space, time it, nothing in the mouth, do not hold them down." },
  { id: "f08", deck: "firstaid", topic: "Diabetic low", front: "Shaky, sweaty, awake diabetic?", back: "If they can swallow: 15–20 g sugar. If unresponsive: no oral sugar, 911, glucagon if trained." },
  { id: "f09", deck: "firstaid", topic: "Burn", front: "Cool a thermal burn with?", back: "Cool water (not ice stuck on the skin). Clean dry cover. 911 for large/face/airway/electrical/chemical." },
  { id: "f10", deck: "firstaid", topic: "Spine", front: "When to protect the spine?", back: "Significant mechanism (fall, dive, crash) plus neck pain, numbness, or unresponsiveness. Jaw-thrust for airway." },
  { id: "f11", deck: "firstaid", topic: "Heat stroke", front: "Heat stroke vs exhaustion?", back: "Stroke: hot and altered — cool fast, 911. Exhaustion: still sensible, rest/cool/fluids if they can drink." },
  { id: "f12", deck: "firstaid", topic: "Good Samaritan", front: "Good Samaritan idea?", back: "Good-faith help within training, not reckless, usually unpaid. Does not cover abandonment or shocking a talking person." },
  { id: "f13", deck: "firstaid", topic: "Abandonment", front: "Abandonment?", back: "You start care, they still need you, you leave without a proper handoff and without a safety reason." },
  { id: "f14", deck: "firstaid", topic: "PPE", front: "Standard precautions?", back: "Treat all blood/body fluids as infectious. Gloves, barriers, hand hygiene, report exposures." },
  { id: "f15", deck: "firstaid", topic: "Impaled", front: "Impaled object?", back: "Stabilize in place unless it blocks the airway. Do not pull it in the field as a habit." },
  { id: "f16", deck: "firstaid", topic: "Tooth", front: "Knocked-out permanent tooth?", back: "Pick up by the crown, keep moist (milk/saline), dentist ASAP. Do not scrub the root." },
  { id: "f17", deck: "firstaid", topic: "Poison", front: "Swallowed poison?", back: "Call Poison Control or 911. Do not guess antidotes or force vomiting." },
  { id: "f18", deck: "firstaid", topic: "Scene", front: "First first-aid action always?", back: "Scene safety (and your PPE). Then consent / implied consent." },
  { id: "f19", deck: "firstaid", topic: "Stroke NPO", front: "Why nothing by mouth in stroke?", back: "They may not swallow safely — aspiration." },
  { id: "f20", deck: "firstaid", topic: "Card", front: "Does this practice lab issue an AHA card?", back: "No. Only an authorized instructor after the official course and skills test can issue a card." }
];
