window.OSHA_FLASHCARDS = [
  { id: "n01", deck: "numbers", topic: "OSH Act", front: "Year the OSH Act was passed?", back: "1970. OSHA opened in 1971 under the Department of Labor." },
  { id: "n02", deck: "numbers", topic: "Fatality report", front: "Report a work-related fatality to OSHA within how long?", back: "8 hours (29 CFR 1904.39)." },
  { id: "n03", deck: "numbers", topic: "Severe injury", front: "Hospitalization, amputation, or loss of an eye — report within?", back: "24 hours." },
  { id: "n04", deck: "numbers", topic: "Contest", front: "Days to contest an OSHA citation?", back: "15 working days from receipt." },
  { id: "n05", deck: "numbers", topic: "300A posting", front: "OSHA 300A posting dates?", back: "February 1 through April 30." },
  { id: "n06", deck: "numbers", topic: "11(c)", front: "Deadline to file an 11(c) whistleblower complaint?", back: "Generally 30 days from the retaliatory act." },
  { id: "n07", deck: "numbers", topic: "Construction fall", front: "General construction fall-protection height?", back: "6 feet (1926.501). Scaffolds 10 ft; steel erection 15 ft." },
  { id: "n08", deck: "numbers", topic: "GI fall", front: "General industry fall-protection height?", back: "4 feet (1910.28) for unprotected sides and edges." },
  { id: "n09", deck: "numbers", topic: "Guardrail height", front: "Construction guardrail top-rail height?", back: "42 inches ± 3 inches (39–45 inches)." },
  { id: "n10", deck: "numbers", topic: "Top rail force", front: "Top-rail strength?", back: "200 pounds. Midrail 150 lb. Toeboard 50 lb." },
  { id: "n11", deck: "numbers", topic: "Toeboard", front: "Minimum toeboard height?", back: "3.5 inches, ≤ 1/4 inch gap above the surface." },
  { id: "n12", deck: "numbers", topic: "Anchorage", front: "PFAS anchorage strength?", back: "5,000 lb per employee, or qualified-person design with a safety factor of at least two." },
  { id: "n13", deck: "numbers", topic: "Free fall", front: "Maximum PFAS free fall?", back: "6 feet, and must not hit a lower level." },
  { id: "n14", deck: "numbers", topic: "Deceleration", front: "PFAS deceleration distance limit?", back: "3.5 feet. Max arresting force 1,800 lb with a harness." },
  { id: "n15", deck: "numbers", topic: "Safety nets", front: "Maximum distance nets may be below the work?", back: "30 feet. Closer is better. Drop-test after install." },
  { id: "n16", deck: "numbers", topic: "Warning line", front: "Warning-line distance from a low-slope roof edge (no equipment)?", back: "6 feet. 10 feet on sides perpendicular to mechanical-equipment travel." },
  { id: "n17", deck: "numbers", topic: "Warning line strength", front: "Warning-line tensile strength and height?", back: "500 lb tensile; flagged every 6 ft; 34–39 inches high." },
  { id: "n18", deck: "numbers", topic: "Hole cover", front: "Hole-cover load rating?", back: "At least twice the intended load (employees/equipment). Vehicle covers: 2× maximum axle load." },
  { id: "n19", deck: "numbers", topic: "Low-slope roof", front: "What slope is “low-slope”?", back: "4:12 or less. Steeper than 4:12 is a steep roof — no warning-line-only system." },
  { id: "n20", deck: "numbers", topic: "Scaffold fall", front: "Scaffold fall-protection height?", back: "10 feet (1926.451(g))." },
  { id: "n21", deck: "numbers", topic: "Scaffold width", front: "Minimum scaffold platform width?", back: "18 inches (with listed exceptions)." },
  { id: "n22", deck: "numbers", topic: "Scaffold factor", front: "Scaffold load safety factor?", back: "Own weight plus 4× the maximum intended load." },
  { id: "n23", deck: "numbers", topic: "Scaffold duty", front: "Light / medium / heavy scaffold ratings?", back: "25 / 50 / 75 pounds per square foot." },
  { id: "n24", deck: "numbers", topic: "4:1 scaffold", front: "When must supported scaffolds be tied/guyed?", back: "When height-to-base exceeds 4:1." },
  { id: "n25", deck: "numbers", topic: "Ladder 4:1", front: "Portable ladder setup ratio?", back: "1 foot out for every 4 feet of working length (~75°)." },
  { id: "n26", deck: "numbers", topic: "Ladder extension", front: "How far must a portable ladder extend above the landing?", back: "3 feet, or secure it and provide a grab device." },
  { id: "n27", deck: "numbers", topic: "Rung spacing", front: "Ladder rung spacing?", back: "10 to 14 inches, uniform." },
  { id: "n28", deck: "numbers", topic: "Stair trigger", front: "A stair or ladder is required at a break in elevation of?", back: "19 inches or more (1926.1051)." },
  { id: "n29", deck: "numbers", topic: "Stair variation", front: "Max variation in riser/tread on a stairway?", back: "1/4 inch." },
  { id: "n30", deck: "numbers", topic: "Stair landing", front: "Landing size and vertical rise?", back: "At least 30 in direction of travel × 22 in wide; landing every 12 feet of rise or less." },
  { id: "n31", deck: "numbers", topic: "Trench 5 ft", front: "Protective system generally required at what trench depth?", back: "5 feet, unless stable rock or a competent person finds no cave-in potential. Still protect if a hazard exists at less than 5 ft." },
  { id: "n32", deck: "numbers", topic: "Trench egress", front: "Egress spacing in trenches 4 ft or deeper?", back: "Within 25 feet of lateral travel." },
  { id: "n33", deck: "numbers", topic: "Spoil", front: "Spoil pile setback?", back: "At least 2 feet from the edge (or use retaining devices)." },
  { id: "n34", deck: "numbers", topic: "Type C slope", front: "Maximum simple slope in Type C soil (<20 ft)?", back: "1½ : 1 (34°). Type B 1:1. Type A ¾:1. No benching in Type C." },
  { id: "n35", deck: "numbers", topic: "20-foot trench", front: "Who designs protection at 20 feet or deeper?", back: "A registered professional engineer (or tabulated data that covers that depth)." },
  { id: "n36", deck: "numbers", topic: "Trench atmosphere", front: "Test atmosphere in excavations greater than?", back: "4 feet, if a hazardous atmosphere could reasonably exist." },
  { id: "n37", deck: "numbers", topic: "Excavation LEL", front: "Hazardous flammable atmosphere in an excavation?", back: "Greater than 20% of the LEL (1926.651). Permit spaces use 10% of LEL (1910.146)." },
  { id: "n38", deck: "numbers", topic: "10-foot rule", front: "Clearance from overhead lines ≤50 kV for unqualified workers?", back: "10 feet. Add 4 inches per 10 kV over 50 kV." },
  { id: "n39", deck: "numbers", topic: "Crane lines", front: "Default crane approach to unknown-voltage overhead lines?", back: "20 feet (up to 350 kV) unless you use Table A with known voltage (1926.1408)." },
  { id: "n40", deck: "numbers", topic: "50 volts", front: "Guard live parts at what voltage?", back: "50 volts or more." },
  { id: "n41", deck: "numbers", topic: "Noise AL / PEL", front: "Noise action level and PEL (8-hour TWA)?", back: "85 dBA action level (hearing conservation). 90 dBA PEL." },
  { id: "n42", deck: "numbers", topic: "Silica", front: "Silica PEL and action level?", back: "50 μg/m³ PEL; 25 μg/m³ action level (8-hour TWA)." },
  { id: "n43", deck: "numbers", topic: "Lead", front: "Construction lead PEL and action level?", back: "50 μg/m³ PEL; 30 μg/m³ action level." },
  { id: "n44", deck: "numbers", topic: "Hex chrome", front: "Hexavalent chromium PEL?", back: "5 μg/m³ (8-hour TWA)." },
  { id: "n45", deck: "numbers", topic: "Oxygen", front: "Acceptable oxygen range for confined-space entry?", back: "19.5% to 23.5%." },
  { id: "n46", deck: "numbers", topic: "LEL permit space", front: "Permit-space flammable limit?", back: "Hazardous atmosphere includes ≥10% of the LEL (1910.146)." },
  { id: "n47", deck: "numbers", topic: "Exit width", front: "Minimum exit-route width?", back: "28 inches at all points (occupant load can require more)." },
  { id: "n48", deck: "numbers", topic: "Extinguisher A / B", front: "Max travel distance to Class A and Class B extinguishers (GI)?", back: "75 feet Class A; 50 feet Class B." },
  { id: "n49", deck: "numbers", topic: "Fire watch", front: "Minimum fire-watch time after hot work?", back: "At least 30 minutes (longer if needed for smoldering)." },
  { id: "n50", deck: "numbers", topic: "Oxygen-fuel storage", front: "Separate oxygen from fuel-gas storage how?", back: "20 feet, or a 5-foot-high 30-minute fire wall." },
  { id: "n51", deck: "numbers", topic: "Acetylene", front: "Maximum acetylene working pressure?", back: "15 psig. Unstable above that in free state." },
  { id: "n52", deck: "numbers", topic: "Grinder rest", front: "Bench-grinder work-rest and tongue-guard gaps?", back: "Work rest ≤ 1/8 inch; tongue guard ≤ 1/4 inch." },
  { id: "n53", deck: "numbers", topic: "Compressed air clean", front: "Max psi for compressed-air cleaning?", back: "30 psi, with chip guarding and PPE. Never blow clothing on the body." },
  { id: "n54", deck: "numbers", topic: "Fan guard", front: "Fan-blade guard opening if less than 7 ft high?", back: "No larger than 1/2 inch." },
  { id: "n55", deck: "numbers", topic: "APF half-mask", front: "APF of a half-mask respirator?", back: "10. Full-facepiece 50 (tight-fitting, with fit test)." },
  { id: "n56", deck: "numbers", topic: "Forklift eval", front: "Forklift operator evaluation interval?", back: "At least every 3 years, and after incidents or unsafe operation." },
  { id: "n57", deck: "numbers", topic: "Unattended PIT", front: "When is a forklift “unattended”?", back: "Operator more than 25 feet away or the truck is out of view." },
  { id: "n58", deck: "numbers", topic: "HAZWOPER 40", front: "General site worker HAZWOPER training?", back: "40 hours plus 3 days supervised field experience. Annual 8-hour refresher." },
  { id: "n59", deck: "numbers", topic: "HAZWOPER 24", front: "Occasional site worker / TSD initial hours (typical)?", back: "24 hours (plus field experience or TSD competency as specified)." },
  { id: "n60", deck: "numbers", topic: "PSM flammables", front: "PSM threshold for flammable liquids/gases in a process?", back: "10,000 pounds (with listed exceptions). Toxics have Appendix A TQs (chlorine 1,500 lb; ammonia 10,000 lb)." },
  { id: "n61", deck: "numbers", topic: "PSM audit / PHA", front: "PSM PHA revalidation and compliance-audit intervals?", back: "PHA at least every 5 years. Compliance audit at least every 3 years." },
  { id: "n62", deck: "numbers", topic: "Log retention", front: "How long keep OSHA 300 / 300A / 301?", back: "5 years after the year they cover." },
  { id: "n63", deck: "numbers", topic: "Form 301 timing", front: "Complete Form 301 within?", back: "7 calendar days of learning a recordable case occurred." },
  { id: "n64", deck: "numbers", topic: "HBV vaccine", front: "When must Hep B vaccine be offered?", back: "After training and within 10 working days of assignment to occupational exposure, at no cost." },
  { id: "n65", deck: "numbers", topic: "NIOSH lift", front: "NIOSH recommended weight limit (ideal lift)?", back: "About 51 pounds, reduced by reach, frequency, and twist. Not an OSHA PEL." },
  { id: "n66", deck: "numbers", topic: "Construction extinguisher", front: "2A extinguisher coverage on a construction site?", back: "One 2A per 3,000 sq ft (or major fraction); 100-foot travel distance (1926.150)." },
  { id: "n67", deck: "numbers", topic: "Safety can", front: "Maximum size of a safety can?", back: "5 gallons, with flash-arresting screen and spring-closing lid." },
  { id: "n68", deck: "numbers", topic: "Steel fall", front: "Subpart R general fall-protection height?", back: "15 feet. Connectors have extra rules from 15–30 feet. CDZ 15–30 feet for decking." },
  { id: "n69", deck: "numbers", topic: "Masonry wall", front: "Brace masonry walls over what height until supported?", back: "8 feet, plus a limited access zone of wall height + 4 feet." },
  { id: "n70", deck: "numbers", topic: "Positioning free fall", front: "Positioning-device maximum free fall?", back: "2 feet (1926.502(e)). Not a substitute for fall arrest when you can fall off the work." },

  { id: "r01", deck: "rights", topic: "Mission", front: "What is OSHA’s mission?", back: "Assure safe and healthful working conditions. Set/enforce standards, training, and assistance." },
  { id: "r02", deck: "rights", topic: "General Duty", front: "What is the General Duty Clause?", back: "OSH Act §5(a)(1): workplace free from recognized hazards likely to cause death or serious harm." },
  { id: "r03", deck: "rights", topic: "5(a)(2)", front: "What does §5(a)(2) require?", back: "Employers must comply with OSHA standards." },
  { id: "r04", deck: "rights", topic: "5(b)", front: "What is the employee duty under the Act?", back: "§5(b): comply with standards applicable to your own actions. The employer still holds primary duty." },
  { id: "r05", deck: "rights", topic: "Complaint", front: "Can you file an OSHA complaint confidentially?", back: "Yes. Anyone can file. You may ask that your name be withheld from the employer." },
  { id: "r06", deck: "rights", topic: "11(c)", front: "What does Section 11(c) protect?", back: "Workers from retaliation for reporting hazards, filing complaints, or participating in OSHA activities." },
  { id: "r07", deck: "rights", topic: "Walkaround", front: "Who may join an OSHA inspection walkaround?", back: "An employee representative. Opening and closing conferences are part of the inspection." },
  { id: "r08", deck: "rights", topic: "Inspection order", front: "OSHA inspection priority order?", back: "Imminent danger → fatality/catastrophe → complaints/referrals → programmed." },
  { id: "r09", deck: "rights", topic: "Willful", front: "What is a willful violation?", back: "Intentional disregard of, or plain indifference to, the requirements. Highest civil penalties." },
  { id: "r10", deck: "rights", topic: "Serious", front: "What is a serious violation?", back: "Substantial probability of death or serious physical harm, and the employer knew or should have known." },
  { id: "r11", deck: "rights", topic: "SDS right", front: "Do workers have a right to SDS?", back: "Yes. Hazard Communication is the “right to know.” SDS must be readily accessible on the shift." },
  { id: "r12", deck: "rights", topic: "Outreach card", front: "Does an OSHA 10/30 quiz app issue a DOL card?", back: "No. Only an authorized trainer after the required course hours. Practice is not the card." },
  { id: "r13", deck: "rights", topic: "State Plan", front: "How strict must a State Plan be?", back: "At least as effective as federal OSHA. It may be stricter. Public employees are covered in State Plan states." },
  { id: "r14", deck: "rights", topic: "Consultation", front: "Is OSHA On-Site Consultation the same as enforcement?", back: "No. Free, confidential help for small/medium employers. No citations, but serious hazards must be fixed." },
  { id: "r15", deck: "rights", topic: "Multi-employer", front: "Who can OSHA cite on a multi-employer site?", back: "Creating, exposing, correcting, and/or controlling employers depending on the facts. GCs often have controlling-employer duties." },
  { id: "r16", deck: "rights", topic: "Refuse work", front: "When may a worker refuse a task?", back: "Reasonable belief of imminent death/serious injury, not enough time for OSHA, and you asked the employer to fix it if possible. Narrow right." },
  { id: "r17", deck: "rights", topic: "300 vs 301", front: "Form 300 vs 301 vs 300A?", back: "300 = log of injuries/illnesses. 301 = incident report. 300A = annual summary posted Feb 1–Apr 30." },
  { id: "r18", deck: "rights", topic: "Recordable", front: "When is an injury recordable?", back: "Death, days away, restriction/transfer, medical treatment beyond first aid, loss of consciousness, or a significant diagnosed injury." },

  { id: "j01", deck: "jobsite", topic: "Focus Four", front: "Name the Focus Four.", back: "Falls, struck-by, caught-in/between, electrocution. Falls are the leading construction killer." },
  { id: "j02", deck: "jobsite", topic: "Hierarchy", front: "Order of the hierarchy of controls?", back: "Elimination → substitution → engineering → administrative → PPE (last line of defense)." },
  { id: "j03", deck: "jobsite", topic: "Competent person", front: "What is a competent person?", back: "Can identify hazards and has authority to correct them (1926.32(f)). Not the same as “qualified person.”" },
  { id: "j04", deck: "jobsite", topic: "Qualified person", front: "What is a qualified person?", back: "Has a recognized degree, certificate, or extensive knowledge/experience and can solve problems related to the subject (1926.32(m))." },
  { id: "j05", deck: "jobsite", topic: "PFAS ABC", front: "Three parts of a personal fall arrest system?", back: "Anchorage, body harness, connecting device. No body belts for arrest." },
  { id: "j06", deck: "jobsite", topic: "Three-point", front: "What is three-point contact on a ladder?", back: "Two hands and one foot, or two feet and one hand, while climbing. Face the ladder." },
  { id: "j07", deck: "jobsite", topic: "GFCI", front: "Why GFCI on construction temporary power?", back: "Trips on small ground-fault current to prevent electrocution. 1926.404(b) — or a documented AEGCP." },
  { id: "j08", deck: "jobsite", topic: "LOTO verify", front: "After applying locks, what must you do?", back: "Verify isolation: try to start / test for energy, then return controls to off. Relieve stored energy." },
  { id: "j09", deck: "jobsite", topic: "One person one lock", front: "Group lockout core rule?", back: "Each authorized employee has personal protection (own lock on hasp or lockbox) until they remove it." },
  { id: "j10", deck: "jobsite", topic: "Suspended load", front: "May you work under a hoisted load?", back: "No. Use tag lines from outside the fall zone. Barricade crane swing radius." },
  { id: "j11", deck: "jobsite", topic: "Red / blue air", front: "Crane/combination air-line colors (from CDL overlap, glad hands)?", back: "Not an OSHA color code for all cranes — but never stand under the load; follow the lift director and tags." },
  { id: "j12", deck: "jobsite", topic: "Cave-in weight", front: "About how heavy is a cubic yard of soil?", back: "Often ~3,000 lb — as much as a small car. Collapse kills in seconds." },
  { id: "j13", deck: "jobsite", topic: "Trench box", front: "Does a trench shield prevent a cave-in outside the box?", back: "No. It protects people inside. Stay in the box. Follow tabulated data and stick-up above the lip." },
  { id: "j14", deck: "jobsite", topic: "811", front: "What do you do before you dig?", back: "Call 811 / one-call, wait for locates, hand-dig in the tolerance zone. Find private site lines too." },
  { id: "j15", deck: "jobsite", topic: "PASS", front: "PASS for an extinguisher?", back: "Pull, Aim (at the base), Squeeze, Sweep. Fight only a small fire with a clear escape path." },
  { id: "j16", deck: "jobsite", topic: "Fire classes", front: "Class A, B, C, D, K?", back: "A ordinary combustibles; B flammable liquids/gases; C energized electrical; D combustible metals; K cooking oils." },
  { id: "j17", deck: "jobsite", topic: "Exit doors", front: "May emergency exits be chained during occupancy?", back: "No. Unlocked from the inside without keys, tools, or special knowledge." },
  { id: "j18", deck: "jobsite", topic: "Permit space", front: "Three parts of a confined-space definition?", back: "Large enough to enter; limited entry/exit; not designed for continuous occupancy. PRCS adds atmosphere, engulfment, configuration, or other serious hazard." },
  { id: "j19", deck: "jobsite", topic: "Test order", front: "Atmosphere test order?", back: "Oxygen, then flammables (LEL), then toxics. Test multiple levels." },
  { id: "j20", deck: "jobsite", topic: "Would-be rescuers", front: "Who dies most often in confined spaces?", back: "Untrained would-be rescuers. Use non-entry retrieval. Never rush in." },
  { id: "j21", deck: "jobsite", topic: "Forklift tip", front: "If a sit-down forklift tips, what should you do?", back: "Stay seated, belt on, lean away from the fall. Do not jump." },
  { id: "j22", deck: "jobsite", topic: "Forklift travel", front: "How do you carry a load on a forklift?", back: "Low, mast tilted back, forks just high enough to clear. No riders on forks." },
  { id: "j23", deck: "jobsite", topic: "Aerial harness", front: "Where do you tie off in a boom lift?", back: "Manufacturer-designated point in the platform/boom — not to an adjacent building (catapult hazard)." },
  { id: "j24", deck: "jobsite", topic: "Scissor rails", front: "May you stand on scissor-lift guardrails?", back: "No. Both feet on the floor. Gate closed. PFAS if manufacturer requires or rails are not used as designed." },
  { id: "j25", deck: "jobsite", topic: "Guards on", front: "Power-tool and machine guards?", back: "Stay on. Point of operation, nip points, chips. LOTO when guards come off for service." },
  { id: "j26", deck: "jobsite", topic: "Ring test", front: "What is an abrasive-wheel ring test?", back: "Tap the wheel; a clear ring vs a dull thud of a crack. Match RPM. Guard on." },
  { id: "j27", deck: "jobsite", topic: "Rebar caps", front: "Do cheap mushroom rebar caps prevent impalement?", back: "Often no. Use listed/tested caps or troughs. Fall protection still applies on formwork/rebar at 6 ft." },
  { id: "j28", deck: "jobsite", topic: "Two bolts", front: "Before unhooking a steel member?", back: "Generally at least two bolts per connection, wrench-tight (or equivalent per 1926.756)." },
  { id: "j29", deck: "jobsite", topic: "Demo survey", front: "Before demolition starts?", back: "Written engineering survey by a competent person. Shut off utilities. Check asbestos/lead." },
  { id: "j30", deck: "jobsite", topic: "High-vis", front: "Work-zone high-visibility?", back: "MUTCD / 1926.201 garments. Night flaggers typically Class 3. Struck-by is Focus Four." },

  { id: "h01", deck: "health", topic: "HazCom 16", front: "How many SDS sections under GHS?", back: "16. Section 2 = hazards; 4 = first aid; 8 = exposure controls/PPE." },
  { id: "h02", deck: "health", topic: "Signal words", front: "GHS signal words?", back: "Danger (more severe) and Warning. Not every chemical has one." },
  { id: "h03", deck: "health", topic: "Pictogram flame-circle", front: "Flame-over-circle pictogram?", back: "Oxidizer. Keep away from fuels. Intensifies fire." },
  { id: "h04", deck: "health", topic: "Skull pictogram", front: "Skull-and-crossbones means?", back: "Acute toxicity (fatal or toxic). Exclamation mark is often “harmful” / irritant." },
  { id: "h05", deck: "health", topic: "Secondary label", front: "When can a workplace bottle skip a full label?", back: "Portable container for immediate use by the person who transferred it, under their exclusive control — no leftovers for the next shift." },
  { id: "h06", deck: "health", topic: "CO", front: "Why is carbon monoxide so dangerous?", back: "Colorless, odorless; binds hemoglobin. Generators and heaters indoors kill. Use CO alarms and ventilation." },
  { id: "h07", deck: "health", topic: "Heat stroke", front: "Heat stroke first actions?", back: "Call 911, cool rapidly (water/ice/shade). Altered mental status is an emergency — not “walk it off.”" },
  { id: "h08", deck: "health", topic: "Heat trio", front: "Basic heat-illness controls?", back: "Water, rest, shade, and acclimatization (first days are the deadliest)." },
  { id: "h09", deck: "health", topic: "Table 1", front: "What is silica Table 1?", back: "Specified exposure-control methods (wet, vacuum, listed respirators) so you may skip monitoring for that task if fully implemented." },
  { id: "h10", deck: "health", topic: "Dry sweep silica", front: "Dry sweeping silica dust?", back: "Generally prohibited where wet methods or HEPA vacuum are feasible. No compressed-air blowing." },
  { id: "h11", deck: "health", topic: "Asbestos", front: "If you hit suspected ACM?", back: "Stop, do not disturb, get a competent person. Class I–IV rules in 1926.1101." },
  { id: "h12", deck: "health", topic: "Lead hygiene", front: "Eating in a lead work area?", back: "No. Change areas, wash, no tobacco. Take-home lead poisons families." },
  { id: "h13", deck: "health", topic: "N95", front: "What does N95 mean?", back: "Not oil-resistant; ≥95% filter efficiency for particles. Does not add oxygen or stop most vapors." },
  { id: "h14", deck: "health", topic: "Beards", front: "Tight-fitting respirator and a beard?", back: "Incompatible if hair breaks the seal. Clean-shaven or use a loose-fitting hooded respirator if APF is enough." },
  { id: "h15", deck: "health", topic: "Seal check vs fit test", front: "User seal check vs annual fit test?", back: "Seal check every donning. Fit test initially, at least annually, and after facial changes. Not the same thing." },
  { id: "h16", deck: "health", topic: "IDLH unknown", front: "If you cannot estimate the exposure?", back: "Treat the atmosphere as IDLH until characterized (1910.134). That means SCBA/SAR, not an N95." },
  { id: "h17", deck: "health", topic: "Universal precautions", front: "Universal precautions means?", back: "Treat all blood and OPIM as infectious. Gloves, sharps containers, Hep B vaccine offer." },
  { id: "h18", deck: "health", topic: "BBP three viruses", front: "Three main occupational bloodborne viruses?", back: "HBV (vaccine exists), HCV, HIV." },
  { id: "h19", deck: "health", topic: "HAZWOPER awareness", front: "Awareness-level HAZMAT role?", back: "Recognize, notify, stay back. Do not contain. Operations = defensive; technician = offensive/source control." },
  { id: "h20", deck: "health", topic: "Level A", front: "EPA/OSHA Level A PPE?", back: "Vapor-tight fully encapsulating suit with SCBA. Highest skin + respiratory protection. Heat stress is severe." },
  { id: "h21", deck: "health", topic: "Buddy hot zone", front: "Hot-zone entry rule in HAZWOPER emergencies?", back: "Buddy system and backup personnel. Nobody enters alone." },
  { id: "h22", deck: "health", topic: "Eyewash", front: "Corrosive splash — eyewash?", back: "Immediate flush in the work area, often 15 minutes per SDS, lids open, then medical care. ANSI Z358.1 ~10 seconds travel is common practice." },
  { id: "h23", deck: "health", topic: "Welding zinc", front: "Metal fume fever often comes from?", back: "Zinc oxide fume — welding/cutting galvanized steel. Ventilate; don’t eat in the plume." },
  { id: "h24", deck: "health", topic: "Oil on oxygen", front: "Oil or grease on oxygen fittings?", back: "Dangerous — can ignite or explode. Keep oxygen equipment clean." },
  { id: "h25", deck: "health", topic: "Hearing STS", front: "What is an STS in a hearing program?", back: "Standard Threshold Shift on audiogram vs baseline. Triggers follow-up under 1910.95 and possible OSHA-log recording under 1904.10." }
];
